# Generated by Django 4.0.4 on 2022-05-06 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docplatform', '0003_workspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='workspace',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='docplatform.workspace'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='workspace',
            field=models.ManyToManyField(blank=True, to='docplatform.workspace'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
