# Generated by Django 4.0.4 on 2022-05-07 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docplatform', '0005_remove_user_workspace_workspace_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='members',
        ),
        migrations.AddField(
            model_name='user',
            name='workspace',
            field=models.ManyToManyField(blank=True, to='docplatform.workspace'),
        ),
    ]
